## 打印版本信息

In [1]:
import torch
torch.__version__

'1.6.0'

## 基本使用方法
##### 创建矩阵

In [3]:
x = torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

##### 随机值

In [7]:
x = torch.rand(5,3)
x

tensor([[0.8224, 0.5112, 0.4224],
        [0.8825, 0.6511, 0.6754],
        [0.8384, 0.2517, 0.8505],
        [0.1463, 0.5074, 0.2227],
        [0.1841, 0.0471, 0.6144]])

##### 全0矩阵

In [12]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

##### 直接传入数据值

In [13]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

##### 打印矩阵的维度

In [15]:
 x.size()

torch.Size([5])

##### 将4x4的转成1维的

In [26]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8) #-1表示自动去计算
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


##### 与numpy 协同工作

In [28]:
x = torch.ones(5)
a = x.numpy() # tensor格式转成numpy格式
a

array([1., 1., 1., 1., 1.], dtype=float32)

In [30]:
import numpy as np
x = np.ones(5)
y = torch.from_numpy(x) #把numpy 转成tensor格式
y

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)